### ISSUE TITLE
New IM medals are causing issues

### ISSUE THREAD

**Issue by MiChAeLoKGB** [Phalynx/WoT-Replay-To-JSON#9]
Individual mission medals cause an issue in which Parser throws "Errors occured: 540".
But when I open the json file, everything seems fine.

You get these for 15, 30, 45 and 60 'perfect' missions - completed with honours for each of the disciplines.
![cmd](https://cloud.githubusercontent.com/assets/6197503/6180885/31281d38-b32b-11e4-8195-12413901504a.png)
Here are three replays in which it happens: https://mega.co.nz/#!80gz3AqZ!mwLgPWl7g_j2DLBcgynCswt5xVEyxi3b77k5xKHbev8
https://www.dropbox.com/s/k52qatirpuydhr8/14220048398897_germany_G103_RU_251_redshire.wotreplay?dl=0

**Comment by eav93** [comment]
Add new achievements:	achievements[495] = 'guerrilla'
	achievements[496] = 'guerrillaMedal'
	achievements[497] = 'infiltrator'
	achievements[498] = 'infiltratorMedal'
	achievements[499] = 'sentinel'
	achievements[500] = 'sentinelMedal'
	achievements[501] = 'prematureDetonation'
	achievements[502] = 'prematureDetonationMedal'
	achievements[503] = 'bruteForce'
	achievements[504] = 'bruteForceMedal'
	achievements[505] = 'awardCount'
	achievements[506] = 'battleTested'
	achievements[507] = 'medalRotmistrov'
	achievements[508] = 'combatCount'
	achievements[509] = 'combatWins'
	achievements[510] = 'successDefenceCount'
	achievements[511] = 'successAttackCount'
	achievements[512] = 'captureEnemyBuildingTotalCount'
	achievements[513] = 'lossOwnBuildingTotalCount'
	achievements[514] = 'resourceCaptureCount'
	achievements[515] = 'resourceLossCount'
	achievements[516] = 'reservedInt32'
	achievements[517] = 'impenetrable'
	achievements[518] = 'reliableComradeSeries'
	achievements[519] = 'reliableComrade'
	achievements[520] = 'maxAimerSeries'
	achievements[521] = 'shootToKill'
	achievements[522] = 'fighter'
	achievements[523] = 'duelist'
	achievements[524] = 'demolition'
	achievements[525] = 'arsonist'
	achievements[526] = 'bonecrusher'
	achievements[527] = 'charmed'
	achievements[528] = 'even'
	achievements[529] = 'aimer'
	achievements[530] = 'wins'
	achievements[531] = 'capturedBasesInAttack'
	achievements[532] = 'capturedBasesInDefence'
	achievements[533] = 'deathTrack'
	achievements[534] = 'deathTrackWinSeries'
	achievements[535] = 'maxDeathTrackWinSeries'

**Comment by MiChAeLoKGB** [comment]
This helped with Superpershing replays just plain not working, but not with IM medals.


![image](https://cloud.githubusercontent.com/assets/6197503/7902035/03c334e6-07a8-11e5-8af0-a86aef183f50.png)

**Comment by eav93** [comment]
achievements[536] = 'firstMerit'
	achievements[537] = 'tankwomen'
	achievements[538] = 'readyForBattleLT'
	achievements[539] = 'readyForBattleMT'
	achievements[540] = 'readyForBattleHT'
	achievements[541] = 'readyForBattleSPG'
	achievements[542] = 'readyForBattleATSPG'
	achievements[543] = 'readyForBattleALL'
	achievements[544] = 'tankwomenProgress'

**Comment by eav93** [comment]
achievements[545] = 'tankwomenProgress'
	achievements[545] = 'xp'

	achievements[547] = 'wins'
	achievements[548] = 'winAndSurvived'
	achievements[549] = 'losses'
	achievements[550] = 'survivedBattles'
	achievements[551] = 'frags'
	achievements[552] = 'frags8p'
	achievements[553] = 'shots'
	achievements[554] = 'directHits'
	achievements[555] = 'spotted'
	achievements[556] = 'damageDealt'
	achievements[557] = 'damageReceived'
	achievements[558] = 'capturePoints'
	achievements[559] = 'droppedCapturePoints'
	achievements[560] = 'originalXP'
	achievements[561] = 'damageAssistedTrack'
	achievements[562] = 'damageAssistedRadio'
	achievements[563] = 'directHitsReceived'
	achievements[564] = 'noDamageDirectHitsReceived'
	achievements[565] = 'piercingsReceived'
	achievements[566] = 'explosionHitsReceived'
	achievements[567] = 'explosionHits'
	achievements[568] = 'piercings'
	achievements[569] = 'potentialDamageReceived'
	achievements[570] = 'damageBlockedByArmor'
	achievements[571] = 'maxXP'
	achievements[572] = 'maxXPVehicle'
	achievements[573] = 'maxFrags'
	achievements[574] = 'maxFragsVehicle'
	achievements[575] = 'maxDamage'
	achievements[576] = 'maxDamageVehicle'

**Comment by eav93** [comment]
achievements[580] = 'battlesCountInAttack'
	achievements[581] = 'damageDealtInAttack'
	achievements[582] = 'killedVehicles'
	achievements[583] = 'lostVehicles'
	achievements[588] = 'operationWinter'
	achievements[589] = 'tacticalAdvantage'
	achievements[590] = 'damageDealtInDefence'
	achievements[591] = 'tacticalSkill'
	achievements[592] = 'secretOperations'
	achievements[593] = 'victoryMarchClubDBID'
	achievements[594] = 'victoryMarchSeries'
	achievements[595] = 'maxVictoryMarchSeries'
	achievements[596] = 'strategicOperations'
	
	achievements[598] = 'victoryMarch'
	achievements[599] = 'testartilleryman'
	achievements[600] = 'fallout'

**Comment by eav93** [comment]
And add this line to function decodeDossierPopups:

**Comment by MiChAeLoKGB** [comment]
Hmm, now it works, at least on 2 out of 3 replays. I know for sure, the one that is getting Incorrect battle Result is ok and was played till end, as user sent me also link to wotreplays page, and it shown all data normally there.

![image](https://cloud.githubusercontent.com/assets/6197503/7958721/432166ac-09f2-11e5-8c27-9b88c4758fe1.png)

**Comment by Ratzee** [comment]
@eav93 How is it possible to extract the newest achievements from the game?
